name: "TNLManager"
main: net.nonswag.tnl.manager.Manager
version: "2.1"
api-version: "1.13"
author: "NonSwag"
website: https://www.thenextlvl.net/
depend:
  - TNLListener
commands:
  plugin:
